### ISSUE TITLE
step #3 in memo of sensorlab-cli is inaccurate

### ISSUE THREAD

**Issue by dbarthel-ol** [Orange-OpenSource/sensorlab-cli#1]
The "memo" command of sensorlab-cli displays instructions for a standard workflow with sensorlab-cli.
The recommendations for step #3 are inaccurate.
The "collector setup" example needs an address and port as arguments.
I'll produce a pull request to fix line 531 of sensorlab-cli.js

**Comment by quentin-ol** [comment]
PR #2 merged.
